[package]
name = "nmr_API"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
worker_queue = {path = "./worker_queue"}
actix-web = "4.2.1"
derive_more = "0.99.17"
